module: SwiftKueryMySQL
author: IBM
github_url: https://github.com/IBM-Swift/SwiftKueryMySQL/

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, SwiftKueryMySQL.xcodeproj, -target, SwiftKueryMySQL, LIBRARY_SEARCH_PATHS=.build/debug]
